name: kiosk
description: Dart gRPC sample client and server.
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.1
  async: '>=1.13.3 <3.0.0'
  grpc:
    path: ./third_party/grpc-dart
  protobuf: ^2.0.0

dev_dependencies:
  test: ^1.3.0
